remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: google-sr
description: Fast and efficient Package for scraping Google search results without the need for an API key. 🚀
show_downloads: false